services:
  db:
    container_name: relay-db
    image: postgres:latest
    environment:
      POSTGRES_DB: relay-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6000:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
