services:
  db:
    image: postgres:latest
    container_name: relay-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: relay-db
    ports:
      - "6000:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
